// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"PandoraPlusHelper/internal/handler"
	"PandoraPlusHelper/internal/repository"
	"PandoraPlusHelper/internal/server"
	"PandoraPlusHelper/internal/service"
	"PandoraPlusHelper/pkg/app"
	"PandoraPlusHelper/pkg/jwt"
	"PandoraPlusHelper/pkg/log"
	"PandoraPlusHelper/pkg/server/http"
	"PandoraPlusHelper/pkg/sid"
	"github.com/google/wire"
)

// Injectors from wire.go:

func NewWire(logger *log.Logger) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt()
	handlerHandler := handler.NewHandler(logger)
	db := repository.NewDB(logger)
	repositoryRepository := repository.NewRepository(logger, db)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	serviceService := service.NewService(transaction, logger, sidSid, jwtJWT)
	openaiAccountRepository := repository.NewOpenaiAccountRepository(repositoryRepository)
	openaiTokenRepository := repository.NewOpenaiTokenRepository(repositoryRepository)
	userRepository := repository.NewUserRepository(repositoryRepository)
	claudeTokenRepository := repository.NewClaudeTokenRepository(repositoryRepository)
	claudeAccountRepository := repository.NewClaudeAccountRepository(repositoryRepository)

	coordinator := service.NewServiceCoordinator(serviceService, openaiTokenRepository, openaiAccountRepository, claudeTokenRepository, claudeAccountRepository)
	openaiAccountService := service.NewOpenaiAccountService(serviceService, openaiTokenRepository, openaiAccountRepository, coordinator)
	openaiTokenService := service.NewOpenaiTokenService(serviceService, openaiTokenRepository, openaiAccountRepository, coordinator)
	userService := service.NewUserService(serviceService, userRepository, openaiTokenRepository, openaiAccountRepository, claudeTokenRepository, claudeAccountRepository, coordinator)
	loginService := service.NewLoginService(serviceService, userRepository, openaiTokenRepository, openaiAccountRepository, claudeTokenRepository, claudeAccountRepository)
	claudeTokenService := service.NewClaudeTokenService(serviceService, claudeTokenRepository, claudeAccountRepository, coordinator)
	claudeAccountService := service.NewClaudeAccountService(serviceService, claudeTokenRepository, claudeAccountRepository, coordinator)

	tokenHandler := handler.NewOpenaiTokenHandler(handlerHandler, openaiTokenService)
	accountHandler := handler.NewOpenaiAccountHandler(handlerHandler, openaiAccountService)
	loginHandler := handler.NewLoginHandler(handlerHandler, loginService)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	claudeTokenHandler := handler.NewClaudeTokenHandler(handlerHandler, claudeTokenService)
	claudeAccountHandler := handler.NewClaudeAccountHandler(handlerHandler, claudeAccountService)

	httpServer := server.NewHTTPServer(logger, jwtJWT, loginHandler, accountHandler, tokenHandler, userHandler, claudeTokenHandler, claudeAccountHandler)
	job := server.NewJob(logger)
	task := server.NewTask(logger, openaiTokenRepository, openaiAccountRepository, claudeTokenRepository, claudeAccountRepository, userRepository, openaiAccountService, claudeAccountService)
	migrate := server.NewMigrate(db, logger)
	appApp := newApp(httpServer, job, task, migrate)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewTransaction, repository.NewOpenaiTokenRepository, repository.NewOpenaiAccountRepository)

var serviceCoordinatorSet = wire.NewSet(service.NewServiceCoordinator)

var serviceSet = wire.NewSet(service.NewService, service.NewUserService, serviceCoordinatorSet, service.NewOpenaiTokenService, service.NewOpenaiAccountService, server.NewTask)

var migrateSet = wire.NewSet(server.NewMigrate)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewOpenaiAccountHandler, handler.NewOpenaiTokenHandler)

var serverSet = wire.NewSet(server.NewHTTPServer, server.NewJob)

// build App
func newApp(httpServer *http.Server, job *server.Job, task *server.Task, migrate *server.Migrate) *app.App {
	return app.NewApp(app.WithServer(httpServer, job, task, migrate), app.WithName("demo-server"))
}
