name: DockerImageBuild

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.HUB_USER }}
          password: ${{ secrets.HUB_PASS }}

      - name: Generate Version
        run: |
          BUILD_VERSION=$(date +%Y%m%d%H%M%S)
          echo $BUILD_VERSION > VERSION
          echo "VERSION=$BUILD_VERSION" >> $GITHUB_ENV
        shell: bash

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.HUB_USER }}/${{ secrets.HUB_REPO }}:${{ env.VERSION }}
            ${{ secrets.HUB_USER }}/${{ secrets.HUB_REPO }}:latest
          platforms: linux/amd64, linux/arm64

